apiVersion: v1
kind: Service
metadata:
  name: am-cluster
  namespace: kube-system
  labels:
    role: alertmanager 
    tier: cluster
spec:
  type: LoadBalancer
  selector:
    role: alertmanager 
    tier: cluster
  ports:
  - name: http
    port: 9093
    targetPort: 9093
    protocol: TCP
