apiVersion: v1
kind: Service
metadata:
  name: graf-prom-cluster
  namespace: kube-system
  labels:
    tier: cluster
    role: grafana
spec:
  type: LoadBalancer
  selector:
    tier: cluster
    role: grafana
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
