apiVersion: v1
kind: Service
metadata:
  name: prom-cluster
  namespace: kube-system
  labels:
    role: prometheus
    tier: cluster
spec:
  type: LoadBalancer
  selector:
    role: prometheus
    tier: cluster
  ports:
  - name: prom
    port: 9090
    targetPort: 9090 
    protocol: TCP
